import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backBtn: {
    position: "absolute",
    top: 40,
    left: 15,
    zIndex: 10,
    backgroundColor: "#f4f4f4",
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  bannerContainer: {
    position: "relative",
    height: 180,
    backgroundColor: "#ddeafd",
    justifyContent: "flex-end",
    alignItems: "stretch",
  },
  banner: {
    width: "100%",
    height: 180,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    resizeMode: "cover",
  },
  avatarWrapper: {
    position: "absolute",
    left: 20,
    bottom: -40,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: "#f4f4f4",
    zIndex: 2,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  editProfileBtn: {
    position: "absolute",
    right: 20,
    bottom: -48,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#aaa",
    zIndex: 2,
  },
  editProfileText: {
    color: "#14171A",
    fontWeight: "bold",
  },
  infoSection: {
    marginTop: 50,
    paddingHorizontal: 20,
  },
  name: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#14171A",
  },
  username: {
    color: "#657786",
    fontSize: 16,
    marginBottom: 4,
  },
  bio: {
    color: "#14171A",
    marginBottom: 10,
  },
  rowInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  location: {
    color: "#657786",
    fontSize: 14,
  },
  date: {
    color: "#657786",
    fontSize: 14,
  },
  dot: {
    marginHorizontal: 5,
    color: "#657786",
    fontSize: 14,
  },
  stats: {
    color: "#14171A",
    fontSize: 15,
    marginTop: 7,
  },
  bold: {
    fontWeight: "bold",
    color: "#14171A",
  },
  tabsRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#e1e8ed",
    marginTop: 10,
    marginBottom: 6,
    backgroundColor: "#f4f4f4",
  },
  tab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
  },
  tabActive: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 3,
    borderColor: "#e0245e",
  },
  tabText: {
    color: "#657786",
    fontWeight: "bold",
    fontSize: 15,
  },
  tabTextActive: {
    color: "#e0245e",
    fontWeight: "bold",
    fontSize: 15,
  },
});
