const tweets = [
    {
      id: "1",
      user: "MarcoElizondo",
      avatar: "https://randomuser.me/api/portraits/men/1.jpg",
      message: "¡React Native es increíble! 🚀🔥",
      comments: 12,
      likes: 150,
      shares: 20,
      destacados: true,
    },
    {
      id: "2",
      user: "JaneDoe",
      avatar: "https://randomuser.me/api/portraits/women/2.jpg",
      message: "Explorando nuevas tecnologías. ¿Alguna recomendación? 🤔asdddddddddddddddddddddddddddd asdasd asd ag a gagagasfasrkl3krtkarekqorkzmf asfmemqif kadfkaf" ,
      comments: 8,
      likes: 95,
      shares: 10,
      destacados: false,
    },
    {
      id: "3",
      user: "TechGuy",
      avatar: "https://randomuser.me/api/portraits/men/3.jpg",
      message: "La inteligencia artificial cambiará el mundo 🌍💡",
      comments: 20,
      likes: 250,
      shares: 50,
      destacados: true,
    },
    {
      id: "4",
      user: "DevMaster",
      avatar: "https://randomuser.me/api/portraits/men/4.jpg",
      message: "El código limpio es la clave del éxito. 🧹💻",
      comments: 5,
      likes: 70,
      shares: 15,
      destacados: false,
    },
    {
      id: "5",
      user: "MarcoElizondo",
      avatar: "https://randomuser.me/api/portraits/men/5.jpg",
      message: "¡React Native es increíble! 🚀🔥",
      comments: 12,
      likes: 150,
      shares: 20,
      destacados: true,
    },
    {
      id: "6",
      user: "JaneDoe",
      avatar: "https://randomuser.me/api/portraits/women/6.jpg",
      message: "Explorando nuevas tecnologías. ¿Alguna recomendación? 🤔",
      comments: 8,
      likes: 95,
      shares: 10,
      destacados: false,
    },
    {
      id: "7",
      user: "TechGuy",
      avatar: "https://randomuser.me/api/portraits/men/7.jpg",
      message: "La inteligencia artificial cambiará el mundo 🌍💡",
      comments: 20,
      likes: 250,
      shares: 50,
      destacados: true,
    },
    {
      id: "8",
      user: "DevMaster",
      avatar: "https://randomuser.me/api/portraits/men/8.jpg",
      message: "El código limpio es la clave del éxito. 🧹💻",
      comments: 5,
      likes: 70,
      shares: 15,
      destacados: false,
    },
  ];

  export default tweets